version: '3.8'

networks:
  monitoring:
    driver: bridge
  front-tier:
  back-tier:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "192.168.11.0/24"
          gateway: "192.168.11.1"

volumes:
  grafana-data: {}
  prometheus-data: {}

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus_serv
    volumes:
      - "./PRODUCCION/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml"
      # Volumen de datos - Prometheus
      - "prometheus-data:/prometheus"
    ports:
      - 9191:9090
    #network_mode: "host"
    networks:
      - monitoring
      #- back-tier
    restart: always
  grafana:
    image: grafana/grafana-enterprise:8.2.6
    container_name: grafana_serv
    env_file: 
      - "./PRODUCCION/.env"
    volumes:
      - "./PRODUCCION/grafana/grafana.ini:/etc/grafana/grafana.ini"
      - "./PRODUCCION/grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yaml"
      # Volumen de datos - Grafana
      - "grafana-data:/var/lib/grafana"
    ports:
      - "3232:3000"
    #network_mode: "host"
    networks:
      - monitoring
      #- back-tier
      #- front-tier
    restart: always