version: '3.8'

networks:
  monitoring:
    driver: bridge

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus_serv
    volumes:
     - "./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml"
    ports:
     - 9191:9090
    networks:
    - monitoring
  
  grafana:
    image: grafana/grafana-enterprise:latest
    container_name: grafana_serv
    volumes:
      - "./grafana/grafana.ini:/etc/grafana/grafana.ini"
      - "./grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yaml"
    ports:
      - 3200:3000
    networks:
    - monitoring
  
  node-exporter:
    image: prom/node-exporter:latest
    container_name: monitoring_node_exporter
    restart: unless-stopped
    expose:
     - 9100
    networks:
    - monitoring