version: '3.8'

networks:
  monitoring:
    driver: bridge

volumes:
  prometheus_data: {}

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus_serv
    volumes:
      - "./PRODUCCION/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml"
    ports:
      - 9191:9090
    networks:
      - monitoring
  
  grafana:
    image: grafana/grafana-enterprise:8.2.6
    container_name: grafana_serv
    volumes:
      - "./PRODUCCION/grafana/grafana.ini:/etc/grafana/grafana.ini"
      - "./PRODUCCION/grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yaml"
    environment:
      GF_SECURITY_ADMIN_USER: user
      GF_SECURITY_ADMIN_PASSWORD: 1234
    ports:
      - 3200:3000
    networks:
      - monitoring
  
  # node-exporter:
  #   image: prom/node-exporter:latest
  #   container_name: monitoring_node_exporter
  #   restart: unless-stopped
  #   expose:
  #    - 9100
  #   networks:
  #   - monitoring