version: '3.8'

networks:
  monitoring:
    driver: bridge

volumes:
  grafana-data: {}
  prometheus-data: {}

services:
  prometheus:
    image: prom/prometheus:v2.9.2
    container_name: prometheus_serv
    volumes:
      - "./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml"
      # Volumen de datos - Prometheus
      - "prometheus-data:/prometheus"
    ports:
      - ${PROM_HOST_PORT}:${PROM_CONTAINER_PORT}
    networks:
      - monitoring
    restart: always
  
  grafana:
    image: grafana/grafana-enterprise:8.2.6
    container_name: grafana_serv
    env_file: 
      - ".grafana-env"
    volumes:
      - "./grafana/grafana.ini:/etc/grafana/grafana.ini"
      - "./grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yaml"
      # Volumen de datos - Grafana
      - "grafana-data:/var/lib/grafana"
    ports:
      - ${GF_HOST_PORT}:${GF_CONTAINER_PORT}
    networks:
      - monitoring
    restart: always