global:
  scrape_interval:      15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  scrape_timeout:       10s # scrape_timeout is set to the global default (10s).
  evaluation_interval:  15s # Evaluate rules every 15 seconds. The default is every 1 minute.

alerting:
  alertmanagers:
  - static_configs:
    - targets: []
    scheme: http
    timeout: 10s

scrape_configs:
- job_name: prometheus
  static_configs:
  - targets: ['localhost:9090']

#- job_name: 'tag'
#  static_configs:
#  - targets: ['ingresar_ip:puerto', 'ingresar_ip:puerto']